import type { Metadata } from "next";
import { Lato, Nunito } from "next/font/google";
import Header from "@/components/layout/header";
import Footer from "@/components/layout/footer";
import "./globals.css";

const getLato = Lato({
  variable: "--font--lato",
  subsets: ["latin"],
  weight: ['400', "700"]
});

const getNunito = Nunito({
  variable: "--font--nunito",
  subsets: ["latin"],
  weight: ['400', "600", "700"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className={`root ${getLato.variable} ${getNunito.variable}`}>
        <Header />
        <main>
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
